const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

async function generatePolicyPDF({ purchase, user, policy }) {
  return new Promise((resolve, reject) => {
    try {
      const receiptsDir = path.resolve(process.cwd(), 'receipts');
      if (!fs.existsSync(receiptsDir)) fs.mkdirSync(receiptsDir, { recursive: true });

      const filename = `policy_${purchase._id.toString()}.pdf`;
      const filePath = path.join(receiptsDir, filename);

      const doc = new PDFDocument({ size: 'A4', margin: 50 });
      const stream = fs.createWriteStream(filePath);
      doc.pipe(stream);

      doc.fontSize(20).text('InsureMithra - Policy Confirmation', { align: 'center' });
      doc.moveDown();

      doc.fontSize(12).text(`Policy Number: ${purchase.policyNumber || ''}`);
      doc.text(`Transaction ID: ${purchase.transactionId}`);
      doc.text(`Date: ${new Date(purchase.createdAt).toLocaleString()}`);
      doc.moveDown();

      doc.fontSize(14).text('Policy Details', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(12).text(`Name: ${policy.name}`);
      doc.text(`Type: ${policy.type}`);
      doc.text(`Model: ${policy.model}`);
      doc.text(`Insurer: ${policy.insurer}`);
      doc.text(`Premium: ₹${policy.premium}`);
      doc.text(`Coverage: ${policy.coverage}`);
      doc.text(`Tenure: ${policy.tenure}`);
      doc.moveDown();

      doc.fontSize(14).text('Purchaser', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(12).text(`Name: ${user.firstName || ''} ${user.lastName || ''}`);
      doc.text(`Email: ${user.email || ''}`);

      doc.moveDown(2);
      doc.fontSize(10).text('This is a simulated policy confirmation generated by the InsureMithra sandbox payment flow.', { align: 'center' });

      doc.end();

      stream.on('finish', () => resolve(filePath));
      stream.on('error', (err) => reject(err));
    } catch (err) {
      reject(err);
    }
  });
}

module.exports = generatePolicyPDF;
